### ISSUE TITLE
How to get snifferLib, AxspsnifferLib ?

### ISSUE THREAD

**Issue by simyongsup** [vamsimg/DocketPlaceClient#1]
Thanks for API
I have some issue !
How to get snifferLib, AxspsnifferLib ?
where is it ?

simyongsup@naver.com
please

thank you

**Comment by vamsimg** [comment]
Hi , it's a paid component here: https://www.eltima.com/products/serial-activex/

**Comment by simyongsup** [comment]
thank u

one more question.
I lack my ability.

I saw that it detect the comport  and  receipt printer?
In the given source, I can't see the serial port controlling.

How to get  connection receipt printer with control comport?

thank u

**Comment by vamsimg** [comment]
See the connection code here https://github.com/vamsimg/DocketPlaceClient/blob/master/client/FormMain.cs

**Comment by simyongsup** [comment]
Hi , it's a paid component here: https://www.eltima.com/products/serial-activex/

What do i have that kind of type   for sniff  ???
serial port sniffer activex control ?
